### ISSUE TITLE
Can find Stream Reader Node

### ISSUE THREAD

**Issue by Kunz-David** [Amorano/Jovimetrix#27]
Hi!

Sorry Im new to ComfyUI so this might be a basic question, but I cant seem to find the STREAM READER node.

I expected it to be here:
![image](https://github.com/Amorano/Jovimetrix/assets/24957764/15ad6722-3999-423a-8083-d30f58e63e40)

I am on a remote Linux machine and I was hoping to capture the camera from the forwarded port. During the installation I was having a issues with the `mido.midi_device_names()` (since I think my machine doesn't have the capabilities), so I commented out lines using it;
https://github.com/Amorano/Jovimetrix/blob/7e4daef6e228d84b0f806262ca0fc023fa52cc94/core/device.py#L434
https://github.com/Amorano/Jovimetrix/blob/7e4daef6e228d84b0f806262ca0fc023fa52cc94/core/device.py#L459

Otherwise, I didn't change the installation or source files.

Can you please help me with this issue? 🙂

**Comment by Amorano** [comment]
Linus is weakly supported in this library. [There are instructions for the pyaudio install, specific to linux](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#pyaudio)

Beyond that I can try to help if you figure out what the problem is and a workaround, but I dont have the resources for that at the moment. I can add it to the list, but that might be a while.

**Comment by Kunz-David** [comment]
Thanks for your quick reply!

> Linux* is weakly supported in this library. [There are instructions for the pyaudio install, specific to linux](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#pyaudio)
>
> Beyond that I can try to help if you figure out what the problem is and a workaround, but I dont have the resources for that at the moment. I can add it to the list, but that might be a while.
> 
> The commenting out the the midi parts should be fine.
> 
> If there is anything else in the log, during the startup, that could help to point to where the problem is that would go a long way to starting to track it down.

Sure, this is the output. I added a few debug lines.
```
$ python main.py
** ComfyUI startup time: 2024-04-20 15:41:01.552694
** Platform: Linux
** Python version: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]
** Python executable: /home/ubuntu/anaconda3/envs/dk-comfy/bin/python
** Log path: /home/ubuntu/david/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: /home/ubuntu/david/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 40514 MB, total RAM 201299 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A100-SXM4-40GB : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
JOV_LOG_LEVEL: WARNING
                 jov ignore node: ['MIDI READER (JOV) 🎹']
                loading: Jovimetrix.core.utility
2024-04-20 15:41:05.060 | WARNING  | Jovimetrix.core.utility:<module>:54 - no gifski support
                        AKASHIC (JOV) 📓
                        ARRAY (JOV) 📚
                        EXPORT (JOV) 📽
                        IMAGE DIFF (JOV) 📏
                        QUEUE (JOV) 🗃
                        ROUTE (JOV) 🚌
                        VALUE GRAPH (JOV) 📈
2024-04-20 15:41:05.061 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.utility
                loading: Jovimetrix.core.animate
                        TICK (JOV) ⏱
                        WAVE GENERATOR (JOV) 🌊
2024-04-20 15:41:05.126 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.animate
                loading: Jovimetrix.core.device
2024-04-20 15:41:05.130 | ERROR    | Jovimetrix.sup.stream:<module>:33 - NO SPOUT GL SUPPORT
2024-04-20 15:41:05.130 | ERROR    | Jovimetrix.sup.stream:<module>:34 - No module named 'SpoutGL'
                        AUDIO DEVICE (JOV) 📺
                        MIDI FILTER EZ (JOV) ❇️
                        MIDI FILTER (JOV) ✳️
                        MIDI MESSAGE (JOV) 🎛️
                        MIDI READER (JOV) 🎹
2024-04-20 15:41:05.144 | WARNING  | Jovimetrix:__init__:299 - 😥 MIDI READER (JOV) 🎹
                        SPOUT WRITER (JOV) 🎥
                        STREAM READER (JOV) 📺
                        STREAM WRITER (JOV) 🎞️
2024-04-20 15:41:05.144 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.device
                loading: Jovimetrix.core.flow
                        COMPARISON (JOV) 🕵🏽
                        DELAY (JOV) ✋🏽
2024-04-20 15:41:05.146 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.flow
                loading: Jovimetrix.core.calc
                        CALC OP BINARY (JOV) 🌟
                        CALC OP UNARY (JOV) 🎲
                        LERP (JOV) 🔰
                        SWAP (JOV) 😵
                        VALUE (JOV) 🧬
2024-04-20 15:41:05.147 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.calc
                loading: Jovimetrix.core.audio
                        LOAD WAVE (JOV) 🎼
                        WAVE GRAPH (JOV) ▶ ılıılı
2024-04-20 15:41:05.148 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.audio
                loading: Jovimetrix.core.compose
                        BLEND (JOV) ⚗️
                        COLOR THEORY (JOV) 🛞
                        CROP (JOV) ✂️
                        PIXEL MERGE (JOV) 🫂
                        PIXEL SPLIT (JOV) 💔
                        PIXEL SWAP (JOV) 🔃
                        STACK (JOV) ➕
                        TRANSFORM (JOV) 🏝️
2024-04-20 15:41:05.150 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.compose
                loading: Jovimetrix.core.create
                        CONSTANT (JOV) 🟪
                        GRADIENT (JOV) 🍧
                        SHAPE GENERATOR (JOV) ✨
                        STEREOGRAM (JOV) 📻
                        STEREOSCOPIC (JOV) 🕶️
                        TEXT GENERATOR (JOV) 📝
2024-04-20 15:41:05.341 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.create
                loading: Jovimetrix.core.adjust
                        ADJUST (JOV) 🕸️
                        COLOR BLIND (JOV) 👁‍🗨
                        COLOR MATCH (JOV) 💞
                        THRESHOLD (JOV) 📉
2024-04-20 15:41:05.342 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.adjust
                loading: Jovimetrix.core.create_glsl
                        GRAYSCALE GLSL (JOV)
                        NOISE GLSL (JOV)
                        PATTERN GLSL (JOV)
                        POLYGON GLSL (JOV)
                        MAP GLSL (JOV)
                        GLSL (JOV) 🍩
                        SELECT RANGE GLSL (JOV)
                        KALEIDOSCOPE GLSL (JOV)
                        MIRROR GLSL (JOV)
                        ROTATE GLSL (JOV)
                        TILER GLSL (JOV)
                        VFX GLSL (JOV)
2024-04-20 15:41:05.347 | INFO     | Jovimetrix:__init__:308 - ✅ Jovimetrix.core.create_glsl
2024-04-20 15:41:05.347 | INFO     | Jovimetrix:__init__:309 - 55 nodes loaded
### Loading: ComfyUI-Manager (V2.19)
### ComfyUI Revision: 2134 [d64e2174] | Released on '2024-04-17'

Import times for custom nodes:
   0.0 seconds: /home/ubuntu/david/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/ubuntu/david/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /home/ubuntu/david/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   1.1 seconds: /home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```
Then after about 30s, the output continues (I didn't notice this as I was writing the issue here before):
```
[ WARN:0@80.736] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@80.736] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
[ WARN:0@80.736] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ERROR:0@80.736] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
[ERROR] An error occurred while retrieving information for the 'STREAM READER (JOV) 📺' node.
Traceback (most recent call last):
  File "/home/ubuntu/david/ComfyUI/server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix/core/device.py", line 81, in INPUT_TYPES
    monitors = monitor_list()
               ^^^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix/sup/stream.py", line 87, in monitor_list
    with mss.mss() as sct:
         ^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/dk-comfy/lib/python3.11/site-packages/mss/factory.py", line 34, in mss
    return linux.MSS(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/dk-comfy/lib/python3.11/site-packages/mss/linux.py", line 288, in __init__
    raise ScreenShotError("$DISPLAY not set.") from None
mss.exception.ScreenShotError: $DISPLAY not set.

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM dmix
[ERROR] An error occurred while retrieving information for the 'AUDIO DEVICE (JOV) 📺' node.
Traceback (most recent call last):
  File "/home/ubuntu/david/ComfyUI/server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix/core/device.py", line 653, in INPUT_TYPES
    Lexicon.DEVICE: (dev_list, {"default": next(iter(dev_list))}),
                                           ^^^^^^^^^^^^^^^^^^^^
StopIteration

FETCH DATA from: /home/ubuntu/david/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'STREAM READER (JOV) 📺' node.
Traceback (most recent call last):
  File "/home/ubuntu/david/ComfyUI/server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix/core/device.py", line 81, in INPUT_TYPES
    monitors = monitor_list()
               ^^^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix/sup/stream.py", line 87, in monitor_list
    with mss.mss() as sct:
         ^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/dk-comfy/lib/python3.11/site-packages/mss/factory.py", line 34, in mss
    return linux.MSS(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/dk-comfy/lib/python3.11/site-packages/mss/linux.py", line 288, in __init__
    raise ScreenShotError("$DISPLAY not set.") from None
mss.exception.ScreenShotError: $DISPLAY not set.

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM dmix
[ERROR] An error occurred while retrieving information for the 'AUDIO DEVICE (JOV) 📺' node.
Traceback (most recent call last):
  File "/home/ubuntu/david/ComfyUI/server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/david/ComfyUI/custom_nodes/Jovimetrix/core/device.py", line 653, in INPUT_TYPES
    Lexicon.DEVICE: (dev_list, {"default": next(iter(dev_list))}),
                                           ^^^^^^^^^^^^^^^^^^^^
StopIteration
```

I think the error is related to the fact that this is a remote machine. What do you think?

> Otherwise, you can also check that your opencv installation is a single opencv installation, as that also causes problems.

This should not be an issue
```bash
$ pip list | grep opencv
opencv-contrib-python 4.9.0.80
opencv-python         4.9.0.80
```

I also included this in the `ignore.txt`:
```
MIDI READER (JOV) 🎹
```

**Comment by Amorano** [comment]
ah yes. So I see two issues from the log.

> 2024-04-20 15:41:05.130 | ERROR    | Jovimetrix.sup.stream:<module>:33 - NO SPOUT GL SUPPORT
> 2024-04-20 15:41:05.130 | ERROR    | Jovimetrix.sup.stream:<module>:34 - No module named 'SpoutGL'
> 

First thing you probablly want to add is JOV_SPOUT=0 to the env. That will turn off the spout search which I assume is not on the remote box, esp [since its Linux and SpoutGL is windows only](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#spout-windows-only).

Second one I see is indeed the audio device search. If it is remote and no actual audio devices, that could explain the problem, same for the monitors = monitor_list()  since it is looking for the computer's devices, yet it could be remote headless.

Even if a machine is headless, it could still have audio, so I cant just make a "JOV_HEADLESS".
Perhaps another ENV var to turn off Monitor searching?

```
$ pip list | grep opencv
opencv-contrib-python 4.9.0.80
opencv-python         4.9.0.80
```

This looks ok, however, you only need the opencv-contrib-python.

Just make sure to check when installing new repositories because:

`opencv_python_headless-4.7.0.72.dist-info`

is another one that can mess things up when mixed in and many repos still use it.
