### ISSUE TITLE
Stream Reader Broken?

### ISSUE THREAD

**Issue by thot-experiment** [Amorano/Jovimetrix#9]
![image](https://github.com/Amorano/Jovimetrix/assets/94414189/36b2ea31-777c-4264-9e9e-0e9d3a13cc34)
Not sure when this broke, I'll try to investigate further, but in case I don't, this is the error I'm getting for this two node graph. I was previously able to stream my webcam to comfy using the same approach. Has the device selection method changed, do I need to do something differently or is this actually a bug?

**Comment by za-wa-n-go** [comment]
There are no errors, but I am still unable to capture from the camera.

**Comment by Amorano** [comment]
This is resolved in the latest push. Make sure you are using only a single instance on the same "URL". Also note you need to now explicitly put in the device #. I have the default at 0, but that may not be the default for your your system(s) camera(s).

please re-open if it is failing in the same way.

**Comment by za-wa-n-go** [comment]
IMPORT FAILED

Traceback (most recent call last):
  File "C:\Product\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Jovimetrix\__init__.py", line 861, in <module>
    session = Session()
              ^^^^^^^^^
  File "C:\Product\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Jovimetrix\__init__.py", line 129, in __call__
    instance = super().__call__(*arg, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Product\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Jovimetrix\__init__.py", line 238, in __init__
    module = importlib.import_module(f"Jovimetrix.nodes.{f.stem}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Jovimetrix\nodes\device.py", line 242
    StreamManager().
                    ^
SyntaxError: invalid syntax

**Comment by Amorano** [comment]
Sorry, there was a literal copy-pasta in the file just before the commit. You should be good.
